### ISSUE TITLE
Component not loading after upgrade to 0.91 +

### ISSUE THREAD

**Issue by sretalla** [felixsteghofer/homeassistant_custom_components#4]
I had the component working well up to the point of upgrade.

I found a reference to the breaking change:
[https://community.home-assistant.io/t/breaking-changes-in-0-91/109772](https://community.home-assistant.io/t/breaking-changes-in-0-91/109772)

I tried the suggested remedy, but have been unable to make it work, still getting this in the logs on startup:
2019-04-09 15:43:58 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.shinobi.camera. Make sure all dependencies are installed Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 183, in _load_file module = importlib.import_module(path) File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "<frozen importlib._bootstrap>", line 1006, in _gcd_import File "<frozen importlib._bootstrap>", line 983, in _find_and_load File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 677, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 728, in exec_module File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed File "/config/custom_components/shinobi/camera.py", line 9, in <module> from homeassistant.components.camera.mjpeg import (CONF_MJPEG_URL, CONF_STILL_IMAGE_URL, MjpegCamera) ModuleNotFoundError: No module named 'homeassistant.components.camera.mjpeg'

I have the structure:
`custom_components
   └── shinobi

       └── __init__.py   (copy of shinobi.py from custom components)

       └── camera.py  (copy of shinobi.py from the camera subdir)

       └── shinobi.py   (copy of shinobi.py from custom components)`

Anything more I can do to help identify what needs changing or to help testing?

**Comment by felixsteghofer** [comment]
please see #5

**Comment by felixsteghofer** [comment]
Hopefully I can have a look at this at the weekend. As mentioned, I am not using shinobi productive any more.
Anyone who can help is very welcome.

**Comment by sretalla** [comment]
Happy to try anything you need tested.

**Comment by sretalla** [comment]
See my pull request for an updated version that works.

**Comment by felixsteghofer** [comment]
@sretalla thx! PR already merged
